// Product Image Mapping
// Add your product images here by slug

export const PRODUCT_IMAGES: Record<string, string> = {
  // COOKING ESSENTIALS
  "cooking-oil-1l": "/images/products/cooking-oil.jpg",
  "cooking-oil-2l": "/images/products/cooking-oil.jpg",
  "jasmine-rice-5kg": "/images/products/rice.jpg",
  "jasmine-rice-25kg": "/images/products/rice.jpg",
  "sugar-1kg": "/images/products/sugar.jpg",
  "brown-sugar-1kg": "/images/products/brown-sugar.jpg",
  "salt-250g": "/images/products/salt.jpg",
  "iodized-salt-1kg": "/images/products/salt.jpg",
  "flour-1kg": "/images/products/flour.jpg",
  "cornstarch-250g": "/images/products/cornstarch.jpg",
  "garlic-100g": "/images/products/garlic.jpg",
  "onion-250g": "/images/products/onion.jpg",
  "ginger-100g": "/images/products/ginger.jpg",

  // EGGS & DAIRY
  "fresh-eggs-30": "/images/products/eggs.jpg",
  "fresh-eggs-12": "/images/products/eggs.jpg",
  "fresh-milk-1l": "/images/products/milk.jpg",
  "fresh-milk-250ml": "/images/products/milk.jpg",
  "butter-225g": "/images/products/butter.jpg",
  "margarine-250g": "/images/products/margarine.jpg",
  "cheese-slices": "/images/products/cheese.jpg",
  "quickmelt-cheese": "/images/products/cheese.jpg",
  "yogurt-125ml": "/images/products/yogurt.jpg",
  "evaporated-milk": "/images/products/evaporated-milk.jpg",
  "condensed-milk": "/images/products/condensed-milk.jpg",

  // MEAT & POULTRY
  "pork-belly-1kg": "/images/products/pork-belly.jpg",
  "pork-liempo-500g": "/images/products/pork-belly.jpg",
  "whole-chicken": "/images/products/chicken.jpg",
  "chicken-breast-500g": "/images/products/chicken-breast.jpg",
  "ground-beef-500g": "/images/products/ground-beef.jpg",
  "beef-cubes-500g": "/images/products/beef.jpg",
  "pork-chop-500g": "/images/products/pork-chop.jpg",
  "chicken-wings-500g": "/images/products/chicken-wings.jpg",
  "chicken-drumstick-500g": "/images/products/chicken-drumstick.jpg",
  "pork-kasim-1kg": "/images/products/pork.jpg",
  "tocino-250g": "/images/products/tocino.jpg",
  "longganisa-250g": "/images/products/longganisa.jpg",

  // CANNED & PACKAGED
  "corned-beef-260g": "/images/products/corned-beef.jpg",
  "corned-beef-150g": "/images/products/corned-beef.jpg",
  "sardines-155g": "/images/products/sardines.jpg",
  "sardines-tomato": "/images/products/sardines.jpg",
  "instant-noodles": "/images/products/noodles.jpg",
  "cup-noodles": "/images/products/cup-noodles.jpg",
  "pancit-canton": "/images/products/pancit-canton.jpg",
  "lucky-me-pancit-canton-chilimansi":
    "/images/products/pancit-chilimansi.jpg",
  "tuna-flakes-180g": "/images/products/tuna.jpg",
  "tuna-chunks-180g": "/images/products/tuna.jpg",
  "spam-340g": "/images/products/spam.jpg",
  "maling-397g": "/images/products/maling.jpg",
  "liver-spread-85g": "/images/products/liver-spread.jpg",
  "tomato-sauce-250g": "/images/products/tomato-sauce.jpg",
  "spaghetti-pasta-500g": "/images/products/pasta.jpg",

  // FROZEN FOODS
  "hotdog-500g": "/images/products/hotdog.jpg",
  "hotdog-jumbo-500g": "/images/products/hotdog.jpg",
  "chicken-nuggets-250g": "/images/products/nuggets.jpg",
  "chicken-nuggets-500g": "/images/products/nuggets.jpg",
  "fish-fillet-500g": "/images/products/fish-fillet.jpg",
  "bangus-boneless-400g": "/images/products/bangus.jpg",
  "pork-siomai-250g": "/images/products/siomai.jpg",
  "beef-siomai-250g": "/images/products/siomai.jpg",
  "ice-cream-1l": "/images/products/ice-cream.jpg",
  "ice-cream-sandwich": "/images/products/ice-cream-sandwich.jpg",

  // BAKERY & SNACKS
  "pandesal-10pcs": "/images/products/pandesal.jpg",
  "pandesal-20pcs": "/images/products/pandesal.jpg",
  "sliced-bread": "/images/products/bread.jpg",
  "whole-wheat-bread": "/images/products/bread.jpg",
  "potato-chips-150g": "/images/products/chips.jpg",
  "potato-chips-60g": "/images/products/chips.jpg",
  "cookies-200g": "/images/products/cookies.jpg",
  "oreo-133g": "/images/products/oreo.jpg",
  "crackers-200g": "/images/products/crackers.jpg",
  "chocolate-bar-50g": "/images/products/chocolate.jpg",
  "ensaymada-5pcs": "/images/products/ensaymada.jpg",

  // BEVERAGES
  "coke-1.5l": "/images/products/coke.jpg",
  "coke-330ml": "/images/products/coke.jpg",
  "sprite-1.5l": "/images/products/sprite.jpg",
  "royal-1.5l": "/images/products/royal.jpg",
  "coffee-3in1-10pcs": "/images/products/coffee.jpg",
  "coffee-3in1-30pcs": "/images/products/coffee.jpg",
  "orange-juice-1l": "/images/products/orange-juice.jpg",
  "apple-juice-1l": "/images/products/apple-juice.jpg",
  "water-500ml-6pack": "/images/products/water.jpg",
  "water-1l-6pack": "/images/products/water.jpg",
  "iced-tea-1l": "/images/products/iced-tea.jpg",
  "powdered-juice-10pcs": "/images/products/powdered-juice.jpg",

  // CONDIMENTS & SAUCES
  "soy-sauce-1l": "/images/products/soy-sauce.jpg",
  "soy-sauce-500ml": "/images/products/soy-sauce.jpg",
  "vinegar-1l": "/images/products/vinegar.jpg",
  "vinegar-500ml": "/images/products/vinegar.jpg",
  "fish-sauce-750ml": "/images/products/fish-sauce.jpg",
  "fish-sauce-350ml": "/images/products/fish-sauce.jpg",
  "ketchup-320g": "/images/products/ketchup.jpg",
  "ketchup-550g": "/images/products/ketchup.jpg",
  "mayonnaise-220ml": "/images/products/mayonnaise.jpg",
  "mayonnaise-470ml": "/images/products/mayonnaise.jpg",
  "oyster-sauce-300ml": "/images/products/oyster-sauce.jpg",
  "hot-sauce-90ml": "/images/products/hot-sauce.jpg",
  "banana-ketchup-320g": "/images/products/banana-ketchup.jpg",

  // HOUSEHOLD ESSENTIALS
  "dish-soap-500ml": "/images/products/dish-soap.jpg",
  "dish-soap-250ml": "/images/products/dish-soap.jpg",
  "laundry-detergent-1kg": "/images/products/detergent.jpg",
  "laundry-detergent-500g": "/images/products/detergent.jpg",
  "fabric-conditioner-900ml": "/images/products/fabric-conditioner.jpg",
  "fabric-conditioner-450ml": "/images/products/fabric-conditioner.jpg",
  "toilet-paper-4rolls": "/images/products/toilet-paper.jpg",
  "toilet-paper-12rolls": "/images/products/toilet-paper.jpg",
  "garbage-bags-10pcs": "/images/products/garbage-bags.jpg",
  "garbage-bags-20pcs": "/images/products/garbage-bags.jpg",
  "all-purpose-cleaner-500ml": "/images/products/cleaner.jpg",
  "bleach-1l": "/images/products/bleach.jpg",
  "alcohol-500ml": "/images/products/alcohol.jpg",
  "hand-soap-250ml": "/images/products/hand-soap.jpg",

  // ADDITIONAL PRODUCTS
  "bacon-250g": "/images/products/bacon.jpg",
  "baked-beans-230g": "/images/products/baked-beans.jpg",
  "bathroom-cleaner-500ml": "/images/products/bathroom-cleaner.jpg",
  "bbq-chips-150g": "/images/products/bbq-chips.jpg",
  "beef-loaf-150g": "/images/products/beef-loaf.jpg",
  "bleach-500ml": "/images/products/bleach.jpg",
  "brown-rice-2kg": "/images/products/brown-rice.jpg",
  "cane-vinegar-1l": "/images/products/vinegar.jpg",
  "century-eggs-4pcs": "/images/products/century-eggs.jpg",
  "cheese-chips-150g": "/images/products/cheese-chips.jpg",
  "cheese-hotdog-500g": "/images/products/hotdog.jpg",
  "chicken-hotdog-500g": "/images/products/hotdog.jpg",
  "chicken-popcorn-250g": "/images/products/chicken-popcorn.jpg",
  "chicken-spread-85g": "/images/products/chicken-spread.jpg",
  "chicken-tenders-300g": "/images/products/chicken-tenders.jpg",
  "coconut-cream-250ml": "/images/products/coconut-cream.jpg",
  "coconut-milk-400ml": "/images/products/coconut-milk.jpg",
  "coconut-oil-500ml": "/images/products/coconut-oil.jpg",
  "coconut-vinegar-500ml": "/images/products/vinegar.jpg",
  "color-safe-bleach-900ml": "/images/products/bleach.jpg",
  "corn-chips-150g": "/images/products/corn-chips.jpg",
  "cream-o-330g": "/images/products/cream-o.jpg",
  "dark-soy-sauce-500ml": "/images/products/soy-sauce.jpg",
  "detergent-bar-380g": "/images/products/detergent-bar.jpg",
  "disinfectant-spray-400ml": "/images/products/disinfectant-spray.jpg",
  "downy-900ml": "/images/products/fabric-conditioner.jpg",
  "fish-balls-500g": "/images/products/fish-balls.jpg",
  "floor-cleaner-1l": "/images/products/floor-cleaner.jpg",
  "gatorade-500ml": "/images/products/gatorade.jpg",
  "glass-cleaner-500ml": "/images/products/glass-cleaner.jpg",
  "glutinous-rice-1kg": "/images/products/rice.jpg",
  "ham-250g": "/images/products/ham.jpg",
  "honey-250ml": "/images/products/honey.jpg",
  "kikiam-500g": "/images/products/kikiam.jpg",
  "liquid-detergent-1l": "/images/products/liquid-detergent.jpg",
  "meat-loaf-170g": "/images/products/meat-loaf.jpg",
  "mountain-dew-1.5l": "/images/products/mountain-dew.jpg",
  "muscovado-sugar-500g": "/images/products/brown-sugar.jpg",
  "nutella-200g": "/images/products/nutella.jpg",
  "olive-oil-250ml": "/images/products/olive-oil.jpg",
  "paper-towel-2rolls": "/images/products/paper-towel.jpg",
  "peanut-butter-250g": "/images/products/peanut-butter.jpg",
  "pepsi-1.5l": "/images/products/pepsi.jpg",
  "piattos-85g": "/images/products/piattos.jpg",
  "pineapple-juice-1l": "/images/products/pineapple-juice.jpg",
  "pocari-sweat-500ml": "/images/products/pocari-sweat.jpg",
  "popcorn-100g": "/images/products/popcorn.jpg",
  "pork-and-beans-230g": "/images/products/pork-and-beans.jpg",
  "pretzels-200g": "/images/products/pretzels.jpg",
  "quail-eggs-24pcs": "/images/products/quail-eggs.jpg",
  "rock-salt-500g": "/images/products/salt.jpg",
  "salted-eggs-6pcs": "/images/products/salted-eggs.jpg",
  "sardines-spanish-style": "/images/products/sardines.jpg",
  "sesame-oil-150ml": "/images/products/sesame-oil.jpg",
  "seven-up-1.5l": "/images/products/sprite.jpg",
  "skyflakes-200g": "/images/products/crackers.jpg",
  "sour-cream-chips-150g": "/images/products/chips.jpg",
  "soy-milk-1l": "/images/products/soy-milk.jpg",
  "sponge-3pcs": "/images/products/sponge.jpg",
  "squid-balls-500g": "/images/products/squid-balls.jpg",
  "steel-wool-6pcs": "/images/products/steel-wool.jpg",
  "sticky-rice-2kg": "/images/products/rice.jpg",
  "strawberry-jam-250g": "/images/products/strawberry-jam.jpg",
  "sweet-soy-sauce-300ml": "/images/products/soy-sauce.jpg",
  "trash-bags-large-10pcs": "/images/products/garbage-bags.jpg",
  "tuna-spread-85g": "/images/products/tuna.jpg",
  "wafer-sticks-200g": "/images/products/wafer-sticks.jpg",
  "wet-wipes-80pcs": "/images/products/wet-wipes.jpg",
  "yakisoba-noodles": "/images/products/noodles.jpg",
  "yakult-5pack": "/images/products/yakult.jpg",
  "cheese-ring-100g": "/images/products/cheese-chips.jpg",
};

// ============================================
// CATEGORY IMAGE MAPPING
// Maps category slug → representative product image
// ============================================
export const CATEGORY_IMAGES: Record<string, string> = {
  "cooking-essentials": "/images/products/cooking-oil.jpg",
  "eggs-dairy": "/images/products/eggs.jpg",
  "meat-poultry": "/images/products/chicken.jpg",
  "canned-packaged": "/images/products/corned-beef.jpg",
  "frozen-foods": "/images/products/nuggets.jpg",
  "bakery-snacks": "/images/products/pandesal.jpg",
  beverages: "/images/products/coke.jpg",
  "condiments-sauces": "/images/products/soy-sauce.jpg",
  household: "/images/products/detergent.jpg",
};

// Helper function to get product image
export function getProductImage(slug: string): string | null {
  return PRODUCT_IMAGES[slug] || null;
}
